version: '3.8'

services:
  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - '8014:80'
    volumes:
      - ./nginx/default_reverseproxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - ddosify

  frontend:
    image: ddosify/selfhosted_frontend:2.7.3
    depends_on:
      - backend
    restart: always
    pull_policy: always
    networks:
      - ddosify

  backend:
    image: ddosify/selfhosted_backend:2.6.9
    depends_on:
      - postgres
      - influxdb
      - redis-backend
      - seaweedfs
    env_file:
      - .env
    networks:
      - ddosify
    restart: always
    pull_policy: always
    command: /workspace/start_scripts/start_app_onprem.sh

  backend-celery-worker:
    image: ddosify/selfhosted_backend:2.6.9
    depends_on:
      - postgres
      - influxdb
      - redis-backend
      - seaweedfs
      - backend
      - rabbitmq-celery-backend
    env_file:
      - .env
    networks:
      - ddosify
    restart: always
    pull_policy: always
    command: /workspace/start_scripts/start_celery_worker.sh

  backend-celery-beat:
    image: ddosify/selfhosted_backend:2.6.9
    depends_on:
      - postgres
      - influxdb
      - redis-backend
      - seaweedfs
      - backend
      - rabbitmq-celery-backend
    env_file:
      - .env
    networks:
      - ddosify
    restart: always
    pull_policy: always
    command: /workspace/start_scripts/start_celery_beat.sh

  alaz-backend:
    image: ddosify/selfhosted_alaz_backend:1.0.5
    depends_on:
      - postgres
      - influxdb
      - redis-backend
      - backend
    env_file:
      - .env
    networks:
      - ddosify
    restart: always
    pull_policy: always
    command: /workspace/start_scripts/start_app_onprem.sh

  alaz-backend-celery-worker-1:
    image: ddosify/selfhosted_alaz_backend:1.0.5
    depends_on:
      - postgres
      - influxdb
      - redis-alaz-backend
      - alaz-backend
      - rabbitmq-celery-backend
      - backend
    env_file:
      - .env
    networks:
      - ddosify
    restart: always
    pull_policy: always
    command: /workspace/start_scripts/start_celery_worker.sh

  alaz-backend-celery-worker-2:
    image: ddosify/selfhosted_alaz_backend:1.0.5
    depends_on:
      - postgres
      - influxdb
      - redis-alaz-backend
      - alaz-backend
      - rabbitmq-celery-backend
      - backend
    env_file:
      - .env
    networks:
      - ddosify
    restart: always
    pull_policy: always
    command: /workspace/start_scripts/start_celery_worker.sh

  alaz-backend-celery-beat:
    image: ddosify/selfhosted_alaz_backend:1.0.5
    depends_on:
      - postgres
      - influxdb
      - redis-alaz-backend
      - alaz-backend
      - rabbitmq-celery-backend
      - backend
    env_file:
      - .env
    networks:
      - ddosify
    restart: always
    pull_policy: always
    command: /workspace/start_scripts/start_celery_beat.sh

  hammermanager:
    ports:
      - "9901:8001"
    image: ddosify/selfhosted_hammermanager:1.2.4
    depends_on:
      - postgres
      - rabbitmq-job
      - rabbitmq-celery
    env_file:
      - .env
    networks:
      - ddosify
    restart: always
    pull_policy: always
    command: /workspace/start_scripts/start_app.sh

  hammermanager-celery-worker:
    image: ddosify/selfhosted_hammermanager:1.2.4
    depends_on:
      - postgres
      - rabbitmq-job
      - rabbitmq-celery
      - hammermanager
    env_file:
      - .env
    networks:
      - ddosify
    restart: always
    pull_policy: always
    command: /workspace/start_scripts/start_celery_worker.sh

  hammermanager-celery-beat:
    image: ddosify/selfhosted_hammermanager:1.2.4
    depends_on:
      - postgres
      - rabbitmq-job
      - rabbitmq-celery
      - hammermanager
    env_file:
      - .env
    networks:
      - ddosify
    restart: always
    pull_policy: always
    command: /workspace/start_scripts/start_celery_beat.sh

  hammer:
    image: ddosify/selfhosted_hammer:1.4.2
    volumes:
      - hammer_id:/root/uuid
    depends_on:
      - rabbitmq-job
      - influxdb
      - hammermanager
      - seaweedfs
    env_file:
      - .env
    networks:
      - ddosify
    restart: always
    pull_policy: always

  hammerdebug:
    image: ddosify/selfhosted_hammer:1.4.2
    volumes:
      - hammerdebug_id:/root/uuid
    depends_on:
      - rabbitmq-job
      - influxdb
      - hammermanager
    env_file:
      - .env
    environment:
      - IS_DEBUG=true
    networks:
      - ddosify
    restart: always
    pull_policy: always

  postgres:
    image: "postgres:13.6"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_scripts/postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - ddosify
    restart: always

  rabbitmq-celery:
    image: "rabbitmq:3.13.0"
    networks:
      - ddosify
    restart: always

  rabbitmq-celery-backend:
    image: "rabbitmq:3.13.0"
    networks:
      - ddosify
    restart: always

  rabbitmq-celery-alaz-backend:
    image: "rabbitmq:3.13.0"
    networks:
      - ddosify
    restart: always

  rabbitmq-job:
    ports:
      - "6672:5672"
    image: "rabbitmq:3.13.0"
    networks:
      - ddosify
    restart: always

  influxdb:
    ports:
      - "9086:8086"
    image: "influxdb:2.6.1"
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./init_scripts/influxdb:/docker-entrypoint-initdb.d
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=ddosify
      - DOCKER_INFLUXDB_INIT_BUCKET=hammerBucket
    env_file:
      - .env
    networks:
      - ddosify
    restart: always

  redis-backend:
    image: "redis:7.2.4"
    volumes:
      - redis_backend_data:/data
    networks:
      - ddosify
    restart: always

  redis-alaz-backend:
    image: "redis:7.2.4"
    volumes:
      - redis_alaz_backend_data:/data
    networks:
      - ddosify
    restart: always

  seaweedfs:
    image: chrislusf/seaweedfs:3.56
    ports:
      - "8333:8333"
    command: 'server -s3 -dir="/data"'
    networks:
      - ddosify
    restart: always
    volumes:
      - seaweedfs_data:/data

  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    command: --config.file=/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles --storage.tsdb.retention=10d
    volumes:
      - ./init_scripts/prometheus/prometheus.yml:/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - ddosify
    restart: always

volumes:
  postgres_data:
  influxdb_data:
  redis_backend_data:
  redis_alaz_backend_data:
  seaweedfs_data:
  hammer_id:
  hammerdebug_id:
  prometheus_data:

networks:
  ddosify:
