global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "backend"
    metrics_path: '/metrics/scrape'
    static_configs:
      - targets: ["alaz-backend:8008"]
    basic_auth:
        username: alaz-backend
        password: jRTyHAbUHYE37hRBgEz
