global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "backend"
    metrics_path: '/alaz/metrics/scrape'
    static_configs:
      - targets: ["backend:8008"]
